### ISSUE TITLE
Claim assets/rewards error

### ISSUE THREAD

**Issue by LateralNZ** [0xNODES/community#16]
Error when claim rewards from system 11. Not from just my end but from every user so it isn't client side error. Hit with following error message. 
![image](https://user-images.githubusercontent.com/93115655/143669104-4a828bc5-cdf0-44c2-9035-d8f4598ec1c1.png)

**Comment by jensonb** [comment]
Hi @LateralNZ , thank you for this bug report! This is a high priority item that we are actively working to resolve. I will keep you updated on here.

**Comment by jensonb** [comment]
hi @LateralNZ,

We have rolled out a fix just now to enable you to claim your rewards. We are still working on a fix for the `CLAIM.ALL_ASSETS` function, so in the mean time we have updated the dapp to allow users to `CLAIM.BIOS_REWARDS` and `CLAIM.ETH_REWARDS`:

![image](https://user-images.githubusercontent.com/19617447/143804903-77ad5818-f685-4d0b-bb37-aabf8d860a9c.png)

This should allow you to claim any rewards that you would like. You are of course welcome to continue to wait until we fix and restore the `CLAIM.ALL_ASSETS` function if you prefer, although I cannot give you an exact timeline on when that issue will be resolved.

Just to make sure we are all on the same page, when you claim your rewards, the rewards will be sent from the system to your wallet. While the rewards are unclaimed, the rewards emitter already includes them in its calculation of rewards distributions. In other words, claiming your rewards will reduce the amount of tokens you have in the system and thus slow your rewards accrual unless you deposit them back into the Kernel. Just want to make sure you understand the functionality of the system right there, since better documentation is another feature that we are still working on.

If you decide to claim your rewards or withdraw some assets, we would love to hear a confirmation that the fixes worked for you.

Thanks again for using 0xNODES and submitting the bug report!

**Comment by LateralNZ** [comment]
Thank you Jenson! Hope you guys can get this worked out quickly, good luck :)

**Comment by jensonb** [comment]
You're welcome!

Just to make sure that was clear, the previous button for `CLAIM.ALL_ASSETS` was a combo of the two buttons we have now. So by using the new `CLAIM.BIOS_REWARDS` and `CLAIM.ETH_REWARDS` you can accomplish the same actions as before, it just requires two system calls instead of one. And yes we will also still be fixing the original feature so that you guys can do that in one call again.
