### ISSUE TITLE
System11 Interface Does not auto-refresh after Unlock button used!

### ISSUE THREAD

**Issue by Mafaku** [0xNODES/community#23]
_Fwd: from Valentijn via Discord_

"The interface does not automatically refresh after unlock (so you can not click deposit) I have to refresh the whole browser..."

Can the dev team please address this QoL issue, thanks in advance! o7

![image](https://user-images.githubusercontent.com/95633034/145093782-b9c646a7-c5ef-4ba6-8887-3c24e9a3290b.png)

**Comment by jensonb** [comment]
Hi @Mafaku, thanks for alerting us to this issue!

Do you have information about what browser/device/wallet this bug was experienced on? To my knowledge the UI does *usually* automatically update once the transaction to unlock the assets has been mined, so there also is a possibility that the transaction was still pending in the mempool (even after the metamask confirmation was finished).

I'm going to have a team member investigate this issue to see what is going on. If you have any additional info on the browser/device/wallet, that would be very helpful in helping us to reproduce the bug.

Thank you again for the feedback!!

**Comment by tomxnodes** [comment]
@Mafaku any browser info available here?

**Comment by Mafaku** [comment]
will check with the community member now!

**Comment by Mafaku** [comment]
User Replied:


   1. Valentijn — Today at 4:55 AM
   Standard chrome (Version 96.0.4664.55 (Official Build) (arm64)) on mac M1
   2. [4:55 AM]
   with metamask

**Comment by Mafaku** [comment]
Fixed
